#' List of official variable names by node
#'
#' Return a list containing the list of the variables names for each SpiGes XML.
#' The names of the list are equivalent of the node names returned by
#'
#' Source file: \url{https://www.bfs.admin.ch/bfs/de/home/statistiken/gesundheit/gesundheitswesen/projekt-spiges.assetdetail.28127962.html}
#'
#' @return a list of variable names
#' @export
spiges_get_name_variables <- function() {
  list(
    Administratives = c('burnr_gesv','abc_fall','geschlecht','alter','alter_U1',
                        'wohnort_medstat','wohnkanton','wohnland','nationalitaet',
                        'eintrittsdatum','eintritt_aufenthalt','eintrittsart','einw_instanz',
                        'liegeklasse','versicherungsklasse','admin_urlaub','chlz',
                        'aufenthalt_ips','beatmung','schwere_score','art_score',
                        'nems','aufenthalt_imc','aufwand_imc','hauptleistungsstelle',
                        'grundversicherung','tarif','austrittsdatum','austrittsentscheid',
                        'austritt_aufenthalt','austritt_behandlung'),
    Neugeborene = c('geburtszeit','vitalstatus','mehrling','geburtsrang',
                    'geburtsgewicht','laenge','missbildungen','fall_id_mutter',
                    'gestationsalter1','gestationsalter2','vorh_schwanger',
                    'vorh_lebendgeburten','vorh_fehlgeburten','vorh_abbrueche',
                    'aufnahmegewicht','kopfumfang'),
    Psychiatrie = c('psy_zivilstand','psy_eintritt_aufenthalt','psy_eintritt_teilzeit',
                    'psy_eintritt_vollzeit','psy_eintritt_arbeitslos','psy_eintritt_hausarbeit',
                    'psy_eintritt_ausbildung','psy_eintritt_reha','psy_eintritt_rente',
                    'psy_eintritt_gesch_arbeit','psy_eintritt_unbekannt','psy_schulbildung',
                    'psy_einweisende_instanz','psy_fu','psy_behandlung',
                    'psy_pp_neuroleptika','psy_pp_depotneuroleptika','psy_pp_antidepressiva',
                    'psy_pp_tranquilizer','psy_pp_hypnotika','psy_pp_antiepileptika',
                    'psy_pp_lithium','psy_pp_substitution','psy_pp_suchtaversion',
                    'psy_pp_antiparkinson','psy_pp_andere','psy_pp_koerper_medi',
                    'psy_entsch_austritt','psy_austritt_aufenthalt',
                    'psy_austritt_behandlung','psy_behandlungsbereich'),
    KostentraegerUnternehmen = c('ktr_typ','ktr_beschr','ktr_60','ktr_61','ktr_62','ktr_65',
                                 'ktr_66','ktr_68','ktr_69','ktr_697','ktr_4001','ktr_4002',
                                 'ktr_4012','ktr_4011','ktr_40_rest','ktr_4051','ktr_4052',
                                 'ktr_3801','ktr_3802','ktr_3811','ktr_3812','ktr_480','ktr_485',
                                 'ktr_486','ktr_10','ktr_20','ktr_21','ktr_23','ktr_24','ktr_25',
                                 'ktr_26','ktr_27','ktr_28','ktr_29','ktr_30','ktr_31_1_5',
                                 'ktr_31_6a1','ktr_31_6a2','ktr_31_6b1','ktr_31_6b2','ktr_31_6b3',
                                 'ktr_31_6b4','ktr_31_6b5','ktr_32','ktr_33','ktr_34','ktr_35',
                                 'ktr_36','ktr_38','ktr_39','ktr_40','ktr_41','ktr_42','ktr_43',
                                 'ktr_44','ktr_45','ktr_77','ktr_nicht_pb','ktr_10_ank','ktr_20_ank',
                                 'ktr_21_ank','ktr_23_ank','ktr_24_ank','ktr_25_ank','ktr_26_ank',
                                 'ktr_27_ank','ktr_28_ank','ktr_29_ank','ktr_30_ank','ktr_31_1_5_ank',
                                 'ktr_31_6a1_ank','ktr_31_6a2_ank','ktr_31_6b1_ank','ktr_31_6b2_ank',
                                 'ktr_31_6b3_ank','ktr_31_6b4_ank','ktr_31_6b5_ank','ktr_32_ank',
                                 'ktr_33_ank','ktr_34_ank','ktr_35_ank','ktr_36_ank','ktr_38_ank',
                                 'ktr_39_ank','ktr_40_ank','ktr_41_ank','ktr_42_ank','ktr_43_ank',
                                 'ktr_44_ank','ktr_45_ank','ktr_77_ank','ktr_44_vkl','ktr_44_rekole','ktr_kosten_65',
                                 'ktr_le_ambulant','ktr_methodik'),
    KostentraegerFall = c('ktr_typ','ktr_beschr','ktr_60','ktr_61','ktr_62','ktr_65',
                          'ktr_66','ktr_68','ktr_69','ktr_697','ktr_4001','ktr_4002',
                          'ktr_4012','ktr_4011','ktr_40_rest','ktr_4051','ktr_4052',
                          'ktr_3801','ktr_3802','ktr_3811','ktr_3812','ktr_480','ktr_485',
                          'ktr_486','ktr_10','ktr_20','ktr_21','ktr_23','ktr_24','ktr_25',
                          'ktr_26','ktr_27','ktr_28','ktr_29','ktr_30','ktr_31_1_5',
                          'ktr_31_6a1','ktr_31_6a2','ktr_31_6b1','ktr_31_6b2','ktr_31_6b3',
                          'ktr_31_6b4','ktr_31_6b5','ktr_32','ktr_33','ktr_34','ktr_35',
                          'ktr_36','ktr_38','ktr_39','ktr_40','ktr_41','ktr_42','ktr_43',
                          'ktr_44','ktr_45','ktr_77','ktr_nicht_pb','ktr_10_ank','ktr_20_ank',
                          'ktr_21_ank','ktr_23_ank','ktr_24_ank','ktr_25_ank','ktr_26_ank',
                          'ktr_27_ank','ktr_28_ank','ktr_29_ank','ktr_30_ank','ktr_31_1_5_ank',
                          'ktr_31_6a1_ank','ktr_31_6a2_ank','ktr_31_6b1_ank','ktr_31_6b2_ank',
                          'ktr_31_6b3_ank','ktr_31_6b4_ank','ktr_31_6b5_ank','ktr_32_ank',
                          'ktr_33_ank','ktr_34_ank','ktr_35_ank','ktr_36_ank','ktr_38_ank',
                          'ktr_39_ank','ktr_40_ank','ktr_41_ank','ktr_42_ank','ktr_43_ank',
                          'ktr_44_ank','ktr_45_ank','ktr_77_ank','ktr_44_vkl','ktr_44_rekole','ktr_kosten_65',
                          'ktr_le_ambulant','ktr_methodik'),
    Diagnose = c('diagnose_id','diagnose_kode','diagnose_seitigkeit',
                 'diagnose_poa','diagnose_zusatz'),
    Behandlung = c('behandlung_id','behandlung_chop','behandlung_seitigkeit',
                   'behandlung_beginn','behandlung_auswaerts','behandlung_bur'),
    Operierende = c('op_gln','op_liste','op_rolle'),
    Medikament = c('medi_id','medi_atc','medi_zusatz','medi_verabreichungsart',
                   'medi_dosis','medi_einheit'),
    Rechnung = c('rech_id','rech_kostentraeger','rech_versicherer',
                 'rech_unfallnr','rech_betrag','rech_tariftyp','rech_tarifcode',
                 'rech_ext_faktor','rech_basispreis','rech_einheit','rech_menge'),
    Patientenbewegung = c('episode_id','episode_beginn','episode_ende','episode_art',
                          'burnr_episode','wiedereintritt_aufenthalt','grund_wiedereintritt'),
    KostentraegerStandort = c('ktr_typ','ktr_beschr','ktr_60','ktr_61','ktr_62','ktr_65',
                              'ktr_66','ktr_68','ktr_69','ktr_697','ktr_4001','ktr_4002',
                              'ktr_4012','ktr_4011','ktr_40_rest','ktr_4051','ktr_4052',
                              'ktr_3801','ktr_3802','ktr_3811','ktr_3812','ktr_480','ktr_485',
                              'ktr_486','ktr_10','ktr_20','ktr_21','ktr_23','ktr_24','ktr_25',
                              'ktr_26','ktr_27','ktr_28','ktr_29','ktr_30','ktr_31_1_5',
                              'ktr_31_6a1','ktr_31_6a2','ktr_31_6b1','ktr_31_6b2','ktr_31_6b3',
                              'ktr_31_6b4','ktr_31_6b5','ktr_32','ktr_33','ktr_34','ktr_35',
                              'ktr_36','ktr_38','ktr_39','ktr_40','ktr_41','ktr_42','ktr_43',
                              'ktr_44','ktr_45','ktr_77','ktr_nicht_pb','ktr_10_ank','ktr_20_ank',
                              'ktr_21_ank','ktr_23_ank','ktr_24_ank','ktr_25_ank','ktr_26_ank',
                              'ktr_27_ank','ktr_28_ank','ktr_29_ank','ktr_30_ank','ktr_31_1_5_ank',
                              'ktr_31_6a1_ank','ktr_31_6a2_ank','ktr_31_6b1_ank','ktr_31_6b2_ank',
                              'ktr_31_6b3_ank','ktr_31_6b4_ank','ktr_31_6b5_ank','ktr_32_ank',
                              'ktr_33_ank','ktr_34_ank','ktr_35_ank','ktr_36_ank','ktr_38_ank',
                              'ktr_39_ank','ktr_40_ank','ktr_41_ank','ktr_42_ank','ktr_43_ank',
                              'ktr_44_ank','ktr_45_ank','ktr_77_ank','ktr_44_vkl','ktr_44_rekole','ktr_kosten_65',
                              'ktr_le_ambulant','ktr_methodik')
  )
}
